# Generated by Django 3.1.7 on 2021-04-15 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='panel_info',
            new_name='user_info',
        ),
    ]
